<?
  if($_SESSION['username']) {
    include_once("navbar.phtml");
    if($_SESSION['is_host'])
      require('dashboard.phtml');
    else
      require('location.phtml');
  } else {
    ?><!DOCTYPE html>
    <html>
    <head>
    <link rel="stylesheet" type="text/css" href="/assets/navbar.css">
    <link rel="stylesheet" type="text/css" href="/assets/login.css">
    <link rel="stylesheet" type="text/css" href="/assets/signup.css">


    </head>
    <body>
    <?
    require('splash.phtml');
  } ?>


</body>
</html>
