<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/assets/navbar.css">
<link rel="stylesheet" type="text/css" href="/assets/login.css">
<link rel="stylesheet" type="text/css" href="/assets/signup.css">


</head>
<body>
    

<div class="hero-image">
    
    <div class="hero-text">

        <div id="center-logo"> <!--Adds the eveet logo to the center -->
            <img src="https://i.imgur.com/fLe7f2x.png" class="center-image"/> <!--links to the logo -->
        </div>

    <h1><span>Why go by yourself?</span></h1>
    
    <a href="/signup" class="button">Sign Up</a>
    <a href="/login" class="button">Log In</a>
    </div>
</div>

<div class = "hero-image2">
    <div class = "hero-text2">
        <h2><span>eveet connects you with fellow concertgoers so you never have to go to another concert by yourself.</span></h2>
    </div>
</div>

<div class = "hero-image3">
    <div class = "hero-text3">
        <h3><span>Search events by location:</span></h3>
        <div class="searchbar">
            <input type="text" placeholder="Enter your Location" name="location" required>

            <button type="submit">Search</button>
        </div>

    </div>
</div>

</body>
</html>
