<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/assets/navbar.css">
<link rel="stylesheet" type="text/css" href="/assets/login.css">
<link rel="stylesheet" type="text/css" href="/assets/signup.css">

</head>
<body>
    




 <table style="width:100%">
  <tr>
    <th><!-- Adds the icon library to be used for the icon navbar from font awesome --> 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="icon-bar">
  <a class="active" href="#"><i class="fa fa-home"></i></a> <!--adds the home icon to the bar-->
  <a href="/userprofile/<?= $_SESSION["username"] ?>"><i class="fa fa-user"></i></a> <!--adds the user profile icon to the bar-->
  <a href="#"><i class="fa fa-search"></i></a><!--adds the search for event icon to the bar-->
  <a href="/logout"><i class="fa fa-sign-out"></i></a> <!--adds the sign out icon to the bar-->
</div> </th>
    <th style="width:246px;"> <div id="logo"> <!--Adds the eveet logo to the top right corner -->
    <img src="https://i.imgur.com/fLe7f2x.png" class="image"/> <!--links to the logo -->

</table> 
    
</div>
</th>
