<div class="hero hero-image">

    <div class="hero-text">

        <div id="center-logo"> <!--Adds the eveet logo to the center -->
            <img src="https://i.imgur.com/fLe7f2x.png" class="center-image"/> <!--links to the logo -->
        </div>

    <h1><span>Why go by yourself?</span></h1>

    <a href="/signup" class="button">Sign Up</a>
    <a href="/login" class="button">Log In</a>
    </div>
</div>

<div class = "hero hero-image2">
    <div class = "hero-text2">
        <h2><span>eveet connects you with fellow concertgoers so you never have to go to another concert by yourself.</span></h2>
    </div>
</div>

<div class = "hero hero-image3">
    <div class = "hero-text3">
        <h3><span>Search events by location:</span></h3>
        <div class="searchbar">
          <form action="/location" method="post">
            <input type="text" placeholder="Enter your Location" name="location" required>

            <input type="submit" value="Search" />
          </form>
          <script>
            let form = document.querySelector('form');
            let field = form.querySelector('input[name="location"]');
            form.addEventListener('submit', e=>{
              e.preventDefault();
              location.href = `/location/${field.value}`;
            })
          </script>
        </div>

    </div>
</div>
