<?php 
include_once("navbar.phtml"); 
?>
<link rel="stylesheet" type="text/css" href="/assets/userprofile.css">
<div class="header">
  <h2><?= $fullname ?></h2>
</div>

<div class="row">
  <div class="column side" style="background-color:#aaa;">
    <div class="flex-vertical-container">
        <div class="flex-horizontal-container-centered">
            <div class="container"></div>
            <div id = 'username'> <p> @<?= $username ?></p></div>
        </div>
        <div><p><?=$description?></p><?php if($isOwner) echo '<a href="/userprofile/', $username, '/edit">Edit</a>';?></div>
    </div>
  </div>
  <div class="column middle" style="background-color:#bbb;">What's going on?</div>
 <!-- <div class="column side" style="background-color:#ccc;">Column</div> !-->
</div>

</div>